# Generated by Django 3.1.2 on 2020-10-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailApp', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
